---
  output: html_document
---
  Data Visualization Project 6: NCAA Division I Men's Basketball Statistics for the 2014-2015 Season
===
  **Bryan Amaefule, Shannon Lu, Kevin Lee**  
  [Shiny Application](https://ba7433.shinyapps.io/DV_SProject)
  
  It's officially November, meaning the start of the college basketball season is just a few weeks away. Last season we saw Duke coach Mike Krzyzewski(yes, that's really how you spell his name) lead his Blue Devils to their sixteenth Final Four appearance, and their fifth National Championship. We saw the (almost)undefeated Kentucky Wildcats have their dream of a perfect season, and spot in the history books, cut short by Frank Kaminsky and the Wisconsin Badgers. With the drama of the 2015-2016 season on the horizon it was only fitting that we choose a baketball-centric subject for this project. We acquired statistics from the 2014-2015 season of NCAA Division I Men's Basketball.
  
We display and interpret all of our visualizations in an interactive app using the Shiny package in R. The app can be found [here](https://ba7433.shinyapps.io/DV_SProject). We supply the code for our UI and Server scripts in their entirety at the bottom of this page to allow the reader to easily reproduce our application.

**Background Information** 

To begin with, here are the statistics supplied in the datset and their abbreviations
  
  AST=Assists 
  
  BLK=Blocks 
  
  DRB=Defensive Rebounds 
  
  FG=Field Goals Made 
  
  FGA=Field Goal Attempts  
  
  FT=Free Throws Made 
  
  FTA=Free Throws Attempted 
  
  G=Games played 
  
  MP=Minutes Played 
  
  ORB=Offensive Rebounds 
  
  PF=Personal Fouls 
  
  PTS=Total Points Scored 
  
  STL=Steals 
  
  ThreeP=Three Pointers Made 
  
  ThreePA=Three Pointers Attempted 
  
The dataset includes other information about the players such as: the school they play for, the conference they play in, the position(s) they play, and their classification(freshman, sophomore, etc.) 

It takes a good amount of skill and talent to make it on to a Division I college basketball team, it also takes quite a bit of versitility. As such, many players have developed skillsets suitable to play more than one position. Players who play multiple positions have primary position listed first then their secondary position, separated by a hyphen. So a player whose position say 'F-C' is primarily a Forward but can switch over to the center position. And a player whose position says 'C-G' is probably Anthony Davis and thus way too good to be playing college basketball in the first place.


###Replicating our Visualizations
 We load the entire data set into our data frame using a simple SQL query: "select * from CBB"; all subsequent data wrangling is done in R using dplyr and tidyr. 

**Bar charts**  
Our first two visualizations are bar charts depicting the scoring output of teams in each conference. We set our reference line to be the pre-calculated average value of the total points scored by each conference. The difference between theses two plots rely in the "fill" parameter. In the first plot we set "fill=CONF" which colors each bar based on the conference it represents. This doesn't add much to the information conveyed by the plot, but it helps to improve clarity. For the second plot we set "fill=POS" which allows us to see just which positions are contributing to most of the scoring output in each conference. 

**Crosstabs**  
In project 4, we were able to create a single comprehensive crosstab using Tableau; however recreating an aestheically pleasing version of this crosstab in R proved to be a lot more challenging than we expected. So instead, we split the infromation into two crosstabs. We create both of these crosstabs using the group_by function. Crosstabs are made in ggplot using the average amount of points scored as the label. We use an interactive slider to allow the user to control the values for the key performance indicators. The default values for the KPI are set to the upper and lower quartile values.

Our first crosstab shows the points by classification for players in the Big 12. We filter the data set to include only schools in the Big 12 and group by school and classification.
```
crosstab <- df %>% 
      filter(CONF == "Big 12") %>% 
      group_by(SCHOOL, CLASS) %>% 
      #summarize(sum_pts = sum(PTS), sum_games = sum(G)) %>% 
      mutate(PPG = PTS / G) %>% 
      summarize(avg_pts = mean(PPG)) %>% 
      mutate(kpi = ifelse(avg_pts <= KPI_Low_Max_value, 'Low', ifelse(avg_pts <= KPI_Medium_Max_value, 'Medium', 'High'))) %>% 
      rename(KPI=kpi)
```

Our second crosstab shows the points scored by players in the Big 12 grouped by school and position.
```
crosstab <- df %>% 
      filter(CONF == "Big 12") %>% 
      group_by(SCHOOL, POS) %>% 
      #summarize(sum_pts = sum(PTS), sum_games = sum(G)) %>% 
      mutate(PPG = PTS / G) %>% 
      summarize(avg_pts = mean(PPG)) %>% 
      mutate(kpi = ifelse(avg_pts <= KPI_Low_Max_value, 'Low', ifelse(avg_pts <= KPI_Medium_Max_value, 'Medium', 'High'))) %>% 
      rename(KPI=kpi)
```

**Scatter plots**  
We have many different scatter plots, so we wont be going through them all. For all of the scatter plots we got rid of players in the data frame whose positions were not listed by using "PNN <- df %>% filter(POS != "null") %>% tbl_df". All of the plots were created using simple ggplot programs. Here is an example of our first plot: Assits by position. The rest of the plots can be found in the Server script at the bottom of the page.

```
plot7 <- ggplot() + 
      coord_cartesian() + 
      scale_x_continuous() +
      scale_y_continuous() +
      labs(title='Rebounds By Position') +
      labs(x="Minutes Played", y=paste("Total Rebounds")) +
      layer(data=PNN, 
            mapping=aes(x=MP, y=TRB, color=POS), 
            stat="identity", 
            stat_params=list(), 
            geom="point",
            geom_params=list(), 
            #position=position_identity()
            position=position_jitter(width=0.3, height=0)
      )
```



**Blended data**  
Our blended data joins our last seasons college basketball data with data from the current NBA season allowing us to visualize how last seasons NCAA superstars are adjusting to the NBA as rookies. We use an inner join to combine the two data sets and create two box plots


###Server Script
```
# server.R
require(jsonlite)
require(RCurl)
require(ggplot2)
require(dplyr)
require(tidyr)
require(shiny)
require(leaflet)
require(shinydashboard)
require(DT)

shinyServer(function(input, output) {
  
  df <- data.frame(fromJSON(getURL(URLencode('skipper.cs.utexas.edu:5001/rest/native/?query="select * from CBB order by pos"'),httpheader=c(DB='jdbc:oracle:thin:@sayonara.microlab.cs.utexas.edu:1521:orcl', USER='C##cs329e_ba7433', PASS='orcl_ba7433', MODE='native_mode', MODEL='model', returnDimensions = 'False', returnFor = 'JSON'), verbose = TRUE) ))
  
  

  
  #Points By Position Bar Chart
  output$pointsbypos <- renderPlot({
    plot2 <- ggplot(df, aes(CONF, PTS, fill=POS)) + geom_bar(stat="identity") + geom_hline(yintercept=23425) + coord_flip()
    
    return(plot2)
    
  })
  
  
  #Points By Division Bar Chart
  output$pointsbydiv <- renderPlot({
    plot3 <- ggplot(df, aes(CONF, PTS, fill=CONF)) + geom_bar(stat="identity") + geom_hline(yintercept=23425) + coord_flip()
    
    return(plot3)
  })
  
  
  #Points By Classification Crosstab
  output$classcrosstab <- renderPlot({
    KPI_Low_Max_value = input$KPI1     
    KPI_Medium_Max_value = input$KPI2
    
    
    crosstab <- df %>% 
      filter(CONF == "Big 12") %>% 
      group_by(SCHOOL, CLASS) %>% 
      #summarize(sum_pts = sum(PTS), sum_games = sum(G)) %>% 
      mutate(PPG = PTS / G) %>% 
      summarize(avg_pts = mean(PPG)) %>% 
      mutate(kpi = ifelse(avg_pts <= KPI_Low_Max_value, 'Low', ifelse(avg_pts <= KPI_Medium_Max_value, 'Medium', 'High'))) %>% 
      rename(KPI=kpi)
    
    #Points by Classification in the Big 12
    plot4 <- ggplot() + 
      coord_cartesian() + 
      scale_x_discrete() +
      scale_y_discrete() +
      labs(title='Points by Classification in the Big 12') +
      labs(x=paste("SCHOOL"), y=paste("CLASS")) +
      layer(data=crosstab, 
            mapping=aes(x=SCHOOL, y=CLASS, label=round(avg_pts, 2)), 
            stat="identity", 
            stat_params=list(), 
            geom="text",
            geom_params=list(colour="black"), 
            position=position_identity()
      ) +
      layer(data=crosstab, 
            mapping=aes(x=SCHOOL, y=CLASS, fill=KPI), 
            stat="identity", 
            stat_params=list(), 
            geom="tile",
            geom_params=list(alpha=0.50), 
            position=position_identity()
      )
    
    return(plot4)
    
  })
  
  
  
  #Points By Position Crosstab
  output$poscrosstab <- renderPlot({
    KPI_Low_Max_value = input$KPI1     
    KPI_Medium_Max_value = input$KPI2
    
    crosstab <- df %>% 
      filter(CONF == "Big 12") %>% 
      group_by(SCHOOL, POS) %>% 
      #summarize(sum_pts = sum(PTS), sum_games = sum(G)) %>% 
      mutate(PPG = PTS / G) %>% 
      summarize(avg_pts = mean(PPG)) %>% 
      mutate(kpi = ifelse(avg_pts <= KPI_Low_Max_value, 'Low', ifelse(avg_pts <= KPI_Medium_Max_value, 'Medium', 'High'))) %>% 
      rename(KPI=kpi)
    
    #Points by Position
    plot5 <- ggplot() + 
      coord_cartesian() + 
      scale_x_discrete() +
      scale_y_discrete() +
      labs(title='Points by Position in the Big 12') +
      labs(x=paste("SCHOOL"), y=paste("POSITION")) +
      layer(data=crosstab, 
            mapping=aes(x=SCHOOL, y=POS, label=round(avg_pts, 2)), 
            stat="identity", 
            stat_params=list(), 
            geom="text",
            geom_params=list(colour="black"), 
            position=position_identity()
      ) +
      layer(data=crosstab, 
            mapping=aes(x=SCHOOL, y=POS, fill=KPI), 
            stat="identity", 
            stat_params=list(), 
            geom="tile",
            geom_params=list(alpha=0.50), 
            position=position_identity()
      )
    
    
    return(plot5)
  })
    
  
  
  output$assistsbypos <- renderPlot({
    
    #PNN = Position Not NUll
    PNN <- df %>% filter(POS != "null") %>% tbl_df
    
    #Assist by Position
    plot6 <- ggplot() + 
      coord_cartesian() + 
      scale_x_continuous() +
      scale_y_continuous() +
      labs(title='Assists By Position') +
      labs(x="Minutes Played", y=paste("Assists")) +
      layer(data=PNN, 
            mapping=aes(x=MP, y=AST, color=POS), 
            stat="identity", 
            stat_params=list(), 
            geom="point",
            geom_params=list(), 
            #position=position_identity()
            position=position_jitter(width=0.3, height=0)
      )
    
    return(plot6)
    
  })
  
  
  output$rebsbypos <- renderPlot({
    #PNN = Position Not NUll
    PNN <- df %>% filter(POS != "null") %>% tbl_df
    
    #Rebounds by Position
    plot7 <- ggplot() + 
      coord_cartesian() + 
      scale_x_continuous() +
      scale_y_continuous() +
      labs(title='Rebounds By Position') +
      labs(x="Minutes Played", y=paste("Total Rebounds")) +
      layer(data=PNN, 
            mapping=aes(x=MP, y=TRB, color=POS), 
            stat="identity", 
            stat_params=list(), 
            geom="point",
            geom_params=list(), 
            #position=position_identity()
            position=position_jitter(width=0.3, height=0)
      )
    
    return(plot7)
    
  })
  
  output$stealsbypos <- renderPlot({
    #PNN = Position Not NUll
    PNN <- df %>% filter(POS != "null") %>% tbl_df

    #Steals by position
    plot8 <- ggplot() + 
      coord_cartesian() + 
      scale_x_continuous() +
      scale_y_continuous() +
      labs(title='Steals By Position') +
      labs(x="Personal Fouls", y=paste("Steals")) +
      layer(data=PNN, 
            mapping=aes(x=as.numeric(as.character(PF)), y=as.numeric(as.character(STL)), color=POS), 
            stat="identity", 
            stat_params=list(), 
            geom="point",
            geom_params=list(), 
            #position=position_identity()
            position=position_jitter(width=0.3, height=0)
      )
    
    return(plot8)
        
  })
  
  output$blocksbypos <- renderPlot({
    #PNN = Position Not NUll
    PNN <- df %>% filter(POS != "null") %>% tbl_df

    #Blocks by Position
    plot9 <- ggplot() + 
      coord_cartesian() + 
      scale_x_continuous() +
      scale_y_continuous() +
      labs(title='Blocks By Position') +
      labs(x="Personal Fouls", y=paste("Blocks")) +
      layer(data=PNN, 
            mapping=aes(x=as.numeric(as.character(PF)), y=as.numeric(as.character(BLK)), color=POS), 
            stat="identity", 
            stat_params=list(), 
            geom="point",
            geom_params=list(), 
            #position=position_identity()
            position=position_jitter(width=0.3, height=0)
      ) 
    
    return(plot9)
  })
  
  output$blending1 <- renderPlot({
    
    KPI_Low_Max_value = 3     
    KPI_Medium_Max_value = 7
    
    CBB <- data.frame(fromJSON(getURL(URLencode(gsub("\n", " ", 'skipper.cs.utexas.edu:5001/rest/native/?query= "select * from CBB;"
  ')), httpheader=c(DB='jdbc:oracle:thin:@sayonara.microlab.cs.utexas.edu:1521:orcl', USER='C##cs329e_ba7433', PASS='orcl_ba7433', MODE='native_mode', MODEL='model', returnDimensions = 'False', returnFor = 'JSON', p1=KPI_Low_Max_value, p2=KPI_Medium_Max_value), verbose = TRUE)))
      
      draft <- data.frame(fromJSON(getURL(URLencode(gsub("\n", " ", 'skipper.cs.utexas.edu:5001/rest/native/?query= "select * from draft;"
                                                         ')), httpheader=c(DB='jdbc:oracle:thin:@sayonara.microlab.cs.utexas.edu:1521:orcl', USER='C##cs329e_ba7433', PASS='orcl_ba7433', MODE='native_mode', MODEL='model', returnDimensions = 'False', returnFor = 'JSON', p1=KPI_Low_Max_value, p2=KPI_Medium_Max_value), verbose = TRUE)))
      
      rooks <- right_join(CBB,draft,by='PLAYER')
      rookies <- rooks %>% mutate(cPPG = PTS.x / G.x) %>% filter(PLAYER != "null")
      
      plot10 <- ggplot(rookies, aes(PLAYER, cPPG, fill=CLASS)) + geom_bar(stat="identity") + coord_flip() + ylab("PPG in College")
    
    
    
    return(plot10)
  })
  
  
  
  
  output$blending2 <- renderPlot({
    
    KPI_Low_Max_value = 3     
    KPI_Medium_Max_value = 7
    
    CBB <- data.frame(fromJSON(getURL(URLencode(gsub("\n", " ", 'skipper.cs.utexas.edu:5001/rest/native/?query= "select * from CBB;"
                                                     ')), httpheader=c(DB='jdbc:oracle:thin:@sayonara.microlab.cs.utexas.edu:1521:orcl', USER='C##cs329e_ba7433', PASS='orcl_ba7433', MODE='native_mode', MODEL='model', returnDimensions = 'False', returnFor = 'JSON', p1=KPI_Low_Max_value, p2=KPI_Medium_Max_value), verbose = TRUE)))
    
    draft <- data.frame(fromJSON(getURL(URLencode(gsub("\n", " ", 'skipper.cs.utexas.edu:5001/rest/native/?query= "select * from draft;"
                                                       ')), httpheader=c(DB='jdbc:oracle:thin:@sayonara.microlab.cs.utexas.edu:1521:orcl', USER='C##cs329e_ba7433', PASS='orcl_ba7433', MODE='native_mode', MODEL='model', returnDimensions = 'False', returnFor = 'JSON', p1=KPI_Low_Max_value, p2=KPI_Medium_Max_value), verbose = TRUE)))
    
    rooks <- right_join(CBB,draft,by='PLAYER')
    rookies <- rooks %>% mutate(cPPG = PTS.x / G.x) %>% filter(PLAYER != "null")
  
    plot11 <- ggplot(rookies, aes(PLAYER, round(as.numeric(as.character(PPG), 2)), fill=CLASS)) + geom_bar(stat="identity") + coord_flip() + ylab("PPG in NBA")
    
    return(plot11)
    
    
  })
  
  
})
```


###User Interface Script
```
#ui.R 

library(shiny)
require(shinydashboard)
require(leaflet)

# Define UI for application that plots random distributions 
dashboardPage(
  # Application title
  dashboardHeader(title = "NCAA Men's Basketball Data", titleWidth = 350),
  dashboardSidebar(width = 350,
                   sidebarMenu(
                     menuItem("Points By Division", tabName = "pointsbydiv", icon = icon("bar-chart")),
                     menuItem("Points By Position", tabName = "pointsbypos", icon = icon("bar-chart")),
                     menuItem("Points By Classification in Big 12", tabName = "classcrosstab", icon = icon("table")),
                     menuItem("Points By Position in Big 12", tabName = "poscrosstab", icon = icon("table")),
                     menuItem("Assists By Position", tabName = "assistsbypos", icon = icon("line-chart")),
                     menuItem("Rebounds By Position", tabName = "rebsbypos", icon = icon("line-chart")),
                     menuItem("Steals By Position", tabName = "stealsbypos", icon = icon("line-chart")),
                     menuItem("Blocks By Position", tabName = "blocksbypos", icon = icon("line-chart")),
                     menuItem("Blended Data: College vs. NBA", tabName = "blending", icon = icon("link"))
                   )
  ),
  dashboardBody(
    tabItems(
      #first tab content
      tabItem(tabName = "pointsbydiv",
              h4("Points by Division: "),
              h5("There are two big barometers in determining how successful a team is: how good are their players, and how tough was their competition? A team with a winning record in some conference full of scrubs like the AEC, isn't going to get the same credit or recognition as a team who battled it out through the grueling SEC or ACC conferences. To get a look at just how these conferences stack up against each other, we've created a bar chart of the total points scored by the schools in each division using the average amount of points and the 95% confidence interval as a reference line."),
              plotOutput("pointsbydiv"),
              h5("We can see the conferences that stand out above the rest. The ACC with powerhouses like Duke, North Carolina, Virginia, and Louisville; and the SEC with the 38-1 Kentucky Wildcats. And if you look right on the reference line you'll see the Big 12 conference, home to the University of Texas at Austin, sitting perfectly at the average.")
      ),
      
      
      tabItem(tabName = "pointsbypos",
              h4("Points by Position: "),
              h5("Prior to the NBA Draft, the two most talked about prospects were Duke's Jahlil Okafor and Kentucky's Karl-Anthony Towns, who both happen to be 7-foot tall, 260 pound athletic freaks-of-nature. However, the Los Angeles Lakers broke-away from their history of drafting big men, and selected Ohio State University's 6'5 point guard D'Angelo Russell with the number 2 pick. The Laker's front office caught a lot of flak for not going big, and only time will tell whether or not they made the right choice. For now, we can visualize the scoring contributions in college basketball by adding the 'position' dimension to color on the previous bar chart."),
              plotOutput("pointsbypos"),
              h5("We can see that a bulk of the scoring comes from Guard and Forward positions with the Centers putting up a few points here and there.")
      ),
      
      
      tabItem(tabName = "classcrosstab",
              h4("Points By Classification in Big 12: "),
              h5("Narrowing our view down to just the Big 12 conference, we can create a crosstab of the average points per game, broken down by school, classification, and position. We use a key performance indicator to classify the scoring performance according to where they fit within the quartiles. Scoring performances within the first quartile are labelled Low, second quartile labelled Below Average, third quartile labelled Above Average, and fourth quartile labelled High. The HPIs are tied to interact sliders so that the user can change them as they see fit."),
              sliderInput("KPI1", 
                          "KPI Low Max value:", 
                          min = 0,
                          max = 5, 
                          value = 3),
              sliderInput("KPI2", 
                          "KPI Medium Max value:", 
                          min = 5,
                          max = 13, 
                          value = 7),
              plotOutput("classcrosstab"),
              h5("Keep in mind that these are averages for ALL players at each position, so a performance like Myles Turners's 10.15 points per game would be averaged with fellow Freshman Jordan Barnett's 1.90 points per game.")
      ),
      
      tabItem(tabName = "poscrosstab",
              h4("Points By Position in Big 12: "),
              h5("This crosstab is similr to the previous one, however players are grouped by position and not their classification. For example, in this case, Myle's Turners number would be averaged with all the other forwards at Texas."),
              sliderInput("KPI1", 
                          "KPI Low Max value:", 
                          min = 0,
                          max = 5, 
                          value = 3),
              sliderInput("KPI2", 
                          "KPI Medium Max value:", 
                          min = 5,
                          max = 13, 
                          value = 7),
              plotOutput("poscrosstab")
      ),
      
      tabItem(tabName = "assistsbypos",
              h5("While the scoreboard ultimately decides who wins or loses the ball game, there is much more to the game of basketball than just scoring points. Players can make their mark on the stat sheets on both offense and defense contributing through assists, rebounds, blocks, and steals."),
              h5("Offensively, players can facilitate by creating scoring opportunities for their teammates and racking up assists. Taller, more athletic players can also snag rebounds of a missed shot, allowing the team another chance at scoring. We plot both the assist and rebound numbers of each player against the amount of minutes they played. To provide a little more insight into how each role contributes, we color each point of the scatter plot by position."),
              h4("Assists by Position: "),
              plotOutput("assistsbypos"),
              h5("It can be seen from the scatter plots that guards facilitate for their teammates at a much higher rate than forwards or centers. This is why a talented guard like D'Angelo Russell can get picked second overall in the draft in front of taller, more athletic players.")
      ),

      tabItem(tabName = "rebsbypos",
              h4("Rebounds by Position: "),
              plotOutput("rebsbypos"),
              h5("The revesre seems to be true for rebounds, as the centers and forwards towering over the competition are able to snag the most rebounds off missed shots")
      ),

      tabItem(tabName = "stealsbypos",
              h5("A similar trend appears in the defensive statistics as the quick, dextruous guards are able to steal the ball by playing the passing lanes or just plain ripping the ball from the guy they're defending. The towering big men, clogging up the area around the basket are more adept at swatting shots that come their way. They block more shots than their less vertically-gifted couterparts."),
              h4("Steals by Position: "),
              plotOutput("stealsbypos")
      ),

      tabItem(tabName = "blocksbypos",
              h4("Blocks by Position: "),
              plotOutput("blocksbypos")
      ),
      
      tabItem(tabName = "blending",
              h4("Blended Data: College Basketball Stars vs. NBA Rookies"),
              h5("Every year, around 60 exceptional college basketball players see their dreams come to fruition as they get drafted into the National Basketball Association. These players, who have been the top dogs on evry team they've been on, are thrust into the gaunlet against some of the best athletes in the world. Egos are shattered as high school phenoms and hometown heroes become role-players and bench warmers. To visualize just how these players transition into the pros, we blended our 2014-2015 college basketball data with data from the current NBA season."),
              plotOutput("blending1"),
              h5("We are only a few weeks into the current NBA season so the sample size is fairly small. However, we are still able to see the growing pains of many of the new NBA recruits."),
              plotOutput("blending2")
      )
      
    )
  )
)

```